steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - frontend/Dockerfile
      - --build-arg
      - VITE_API_URL=${_API_URL}
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY

